name: Build and Release CS2-SimpleMenuPlugin

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build plugin
        run: dotnet build simplemenuplugin.csproj -c Release

      - name: Package plugin
        run: |
          mkdir -p plugins/SimpleMenuPlugin
          cp ./bin/Release/net8.0/* plugins/SimpleMenuPlugin/
          zip -r simplemenuplugin.zip plugins

      - name: Create GitHub Release
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --title "SimpleMenuPlugin $GITHUB_REF_NAME" \
            --notes "Automated release of SimpleMenuPlugin version $GITHUB_REF_NAME" \
            simplemenuplugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}