name: Build and Release CS2 Plugin

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build plugin
        run: dotnet build simplemenuplugin.csproj -c Release

      - name: Zip plugin files into plugins/SimpleMenuPlugin/
        run: |
          mkdir -p plugins/SimpleMenuPlugin
          cp ./bin/Release/net8.0/* plugins/SimpleMenuPlugin/
          zip -r simplemenuplugin.zip plugins

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: SimpleMenuPlugin${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./simplemenuplugin.zip
          asset_name: simplemenuplugin.zip
          asset_content_type: application/zip