name: Build and Release CS2 Plugin

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build plugin
        run: dotnet build simplemenuplugin.csproj -c Release

      - name: Zip plugin files into plugins/SimpleMenuPlugin/
        run: |
          mkdir -p plugins/SimpleMenuPlugin
          cp ./bin/Release/net8.0/* plugins/SimpleMenuPlugin/
          zip -r simplemenuplugin.zip plugins

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleMenuPlugin
          path: simplemenuplugin.zip